build:
  image: gcc
  stage: build
  before_script:
    - apt update && apt -y install make
  script:
    - make

deploy:
  image: python
  stage: deploy
  rules:
    - when: manual
  before_script:
    - pip install requests
    - apt update && apt -y install zip
  script:
    - mkdir deploy
    - cp include/* src/* deploy
    - zip deploy.zip deploy/*
    - python upload.py 269 deploy.zip $SAIBLO_PASSWORD
  
