# TODO Start: [Student] Complete Dockerfile
FROM python:3.9

ENV DEPLOY=1

WORKDIR /app

COPY . /app

RUN pip install coverage -i https://pypi.tuna.tsinghua.edu.cn/simple/

# TODO End: [Student] Complete Dockerfile